### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by NamelessLeaf** [TheEpicBlock/immersive-cursedness#16] opened 2021-04-22 13:24 UTC

**Comment by TheEpicBlock** [comment] 2021-04-22 20:00
Do you have Fabric Api installed? Please attach a crash log otherwise. I can't help without context.

**Comment by tjalp** [comment] 2021-04-22 20:10
I've got the same problem. Here are my logs
```
[22:07:57] [main/INFO]: Loading for game Minecraft 1.16.5
[22:07:57] [main/INFO]: [FabricLoader] Loading 53 mods: fabric-renderer-api-v1@0.4.2+2868a2287d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.2, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, lithium@0.6.4, fabric-object-builder-api-v1@1.9.4+9354966b7d, fabric-dimensions-v1@2.0.6+9354966b7d, immersive-cursedness@1.3.0, java@11, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, starlight@fabric-1.0.0-RC1-59d1f21, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.3.0+2868a2287d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.33.0+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, minecraft@1.16.5, fabricproxy@1.4.7, fabric-screen-handler-api-v1@1.1.5+9354966b7d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-command-api-v1@1.1.1+351679a77d, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-rendering-v1@1.6.0+2868a2287d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-resource-loader-v0@0.4.6+2868a2287d, autoconfig1u@3.3.1, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, worldedit@7.2.4+5723-e3bfc64, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.7+2868a2287d, fabric-models-v0@0.3.0+bc7a746f7d, fabric-object-builders-v0@0.7.2+ca58154a7d
[22:07:57] [main/WARN]: Mod `starlight` (fabric-1.0.0-RC1-59d1f21) does not respect SemVer - comparison support is limited.
[22:07:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/container/fabric-launch.jar Service=Knot/Fabric Env=SERVER
[22:08:01] [main/INFO]: Loaded configuration file for Lithium: 80 options available, 0 override(s) found
[22:08:02] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[22:08:02] [main/INFO]: Velocity support injected: one.oktw.mixin.velocity.ServerLoginNetworkHandlerMixin
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:52)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:108)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:64)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62)
        ... 2 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
        ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
        ... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at net.minecraft.class_5464.<clinit>(class_5464.java:93)
        at net.minecraft.class_5458.method_30571(class_5458.java:46)
        at net.minecraft.class_5458.method_30566(class_5458.java:75)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at net.minecraft.class_5458.<clinit>(class_5458.java:74)
        at net.minecraft.class_2378.<clinit>(class_2378.java:237)
        at net.minecraft.class_2966.method_12851(class_2966.java:42)
        at net.minecraft.server.Main.main(Main.java:87)
        ... 14 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinError: Encountered undecorated Accessor method in immersive-cursedness.mixins.json:ServerChunkManagerInvoker applying to net.minecraft.class_3215
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.isAlreadyMerged(MixinApplicatorStandard.java:632)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.mergeMethod(MixinApplicatorStandard.java:548)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1054)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
        ... 28 more
```

**Comment by TheEpicBlock** [comment] 2021-04-22 20:25
I believe this is the result of Mixin#430, which Mixin has fixed. Can you confirm if updating Fabric Loader fixes this?

**Comment by tjalp** [comment] 2021-04-22 20:29
I just updated my `fabric-server-launch` file and it still seems to happen.

**Comment by NamelessLeaf** [comment] 2021-04-22 20:32
Epic block where would I get the new fabric loader

**Comment by NamelessLeaf** [comment] 2021-04-22 20:32
Nvm

**Comment by NamelessLeaf** [comment] 2021-04-22 20:38
Yep same thing is happening for me

**Comment by NamelessLeaf** [comment] 2021-04-22 20:39
I also updated the api

**Comment by TheEpicBlock** [comment] 2021-04-28 16:57
Duplicate of #11

**Closed by TheEpicBlock** 2021-04-28 16:57 UTC
